#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

date

# If we're uploading (which local/dev indexing runs don't do), then we don't
# want to upload the information regarding the staged submodule. So we
# temporarily revert that change, upload the tarball, and then re-apply the
# change.
$CONFIG_REPO/comm-central/submodule-rm

echo Uploading comm-central
pushd $INDEX_ROOT
tar --exclude='comm-central/mozilla' -cf comm-central.tar comm-central
python $AWS_ROOT/upload.py $INDEX_ROOT/comm-central.tar searchfox.repositories comm-central.tar
rm comm-central.tar
popd

# And now that the upload is done, let's re-add the submodule.
$CONFIG_REPO/comm-central/submodule-add

date

echo Uploading comm-central blame
pushd $INDEX_ROOT
tar cf comm-central-blame.tar comm-central-blame
python $AWS_ROOT/upload.py $INDEX_ROOT/comm-central-blame.tar searchfox.repositories comm-central-blame.tar
rm comm-central-blame.tar
popd

date
